# Shell variables
# Generated by 'wal'
wallpaper='/home/nekurill/Pictures/wallpaper/OceanGirl.jpg'

# Special
background='#091019'
foreground='#e4ecf1'
cursor='#e4ecf1'

# Colors
color0='#091019'
color1='#4C7694'
color2='#609FAB'
color3='#5498C0'
color4='#AFB7AD'
color5='#E3CAA9'
color6='#EED6B4'
color7='#e4ecf1'
color8='#9fa5a8'
color9='#4C7694'
color10='#609FAB'
color11='#5498C0'
color12='#AFB7AD'
color13='#E3CAA9'
color14='#EED6B4'
color15='#e4ecf1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
