--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nekurill/Pictures/wallpaper/OceanGirl.jpg"

-- Special
background="#091019"
foreground="#e4ecf1"
cursor="#e4ecf1"

-- Colors
color0="#091019"
color1="#4C7694"
color2="#609FAB"
color3="#5498C0"
color4="#AFB7AD"
color5="#E3CAA9"
color6="#EED6B4"
color7="#e4ecf1"
color8="#9fa5a8"
color9="#4C7694"
color10="#609FAB"
color11="#5498C0"
color12="#AFB7AD"
color13="#E3CAA9"
color14="#EED6B4"
color15="#e4ecf1"
