#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"


sxhkd &
picom -f &
xsetroot -cursor_name left_ptr &
xrandr -s 1920x1080 &
wal -R &
bash $HOME/.config/polybar/launch.sh &


bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          10

bspc config single_monocle	     false
bspc config paddingless_monocle	 false
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.5

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color3"

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config top_padding 33

bspc rule -a TelegramDesktop state=floating rectangle=750x900+1120+90
#bspc rule -a Thunar state=floating rectangle=800x450+80+550




